[project]
name = "bounded-contexts-linter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
flake8 = [
    "flake8>=7.2.0",
]
[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
